### ISSUE TITLE
Recreate the functionality of the last known build

### ISSUE THREAD

**Issue by lgartrell** [YCPRadioTelescope/TelescopeVisualization#104]
## Work needed to be done
Simulator needs to take commands from the control room, the current code does not

**Comment by YCPjsteck** [comment]
We have our hands on the latest source. 😎

**Comment by YCPjsteck** [comment]
Resolved by https://github.com/YCPRadioTelescope/TelescopeVisualization/commit/1ad51ce05cc9a6f83f8a3448eb44d62f2c94aadb.
