### ISSUE TITLE
Constant Spinning after JOG commands

### ISSUE THREAD

**Issue by davidmchugh2000** [YCPRadioTelescope/TelescopeVisualization#123]
After setting up Dylan's fresh environment we JOGGED back and forth. The controlled stop was selected and it was set to move at 0.6 RPM.  "Deactivate Maunaul Control" was still appearing as we were still in the JOG menu. We had JOGGED the telescope through itself performing a movement that shouldn't be allowed (CR currently working on this). We then performed the "snow dump" script which spun the telescope in circles through itself (X-axis). The same happened with the "Home" script.

**Comment by YCPjsteck** [comment]
I'll attempt to replicate this later.
