### ISSUE TITLE
Extremely Large File Size

### ISSUE THREAD

**Issue by Derek-Herr77** [YCPRadioTelescope/TelescopeVisualization#143]
-The current size of the project is 11.1 GB which is extremely large for a project of this size. Find the reason why and see if it can be fixed.

**Comment by YCPjsteck** [comment]
I was able to significantly shrink the simulation branch to only about a gig be clearing out unused files. From what I could tell, there are a lot of unused assets that are a part of the project.

**Comment by Derek-Herr77** [comment]
Removed unused assets, Total project Size is now 5.5gb simulation and VR, fixed with milestone 2
