### ISSUE TITLE
The simulation spins endlessly if a movement goes through 0°

### ISSUE THREAD

**Issue by pdnelson** [YCPRadioTelescope/TelescopeVisualization#85]
This is for the simulation that connects and moves from commands received from the control room.

This is happening because the simulation appears to do its own movement calculation, and the "current" position (in the top right) is already normalized. If it's at position 10, needs to move to 350, and moves -20 to get there, it will be expecting to arrive at position -10, but because of the automatic normalization, as soon as it crosses 0 degrees, it will roll over to 359, never reaching -10. So it will just spin endlessly.

**Comment by YCPjsteck** [comment]
Resolved by 21a9188.
