### ISSUE TITLE
Photon-Coaster (audio/visual tour on a rollercoaster type ride in VR)

### ISSUE THREAD

**Issue by JmyerYCP** [YCPRadioTelescope/TelescopeVisualization#9]
- A "sitdown" mode where the user can play the role of light coming from the atmosphere and then into the telescope through all of the processes/wires and finally to the screen of the computer.
- Could have an audio overlay explaining the parts like a tour of the telescope.
- I'm not sure how difficult this would be to implement so it probably won't be finished this semester.

**Comment by YCPjsteck** [comment]
This idea seems to be split between #62 and #68 now.
